# Use a Node.js base image
FROM node:latest

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Grant execution permissions to PotreeConverter.exe
RUN chmod +x /convertor/PotreeConverter.exe

# Expose the port the app runs on
EXPOSE 5000

# Command to run the Node.js server
CMD ["node", "index.js"]
